### ISSUE TITLE
Alsa: wrong sample_size if multi channel

### ISSUE THREAD

**Issue by mse2** [rhdunn/pcaudiolib#11]
`#define FORMAT(srcfmt, dstfmt, size) case srcfmt: pcm_format = dstfmt; self->sample_size = size; break;
`
probably should be
`#define FORMAT(srcfmt, dstfmt, size) case srcfmt: pcm_format = dstfmt; self->sample_size = size*channels; break;
`
A patched version is here:
https://gitlab.com/mseide-msegui/pcaudiolib

**Comment by rhdunn** [comment]
I have merged the fix for this. Thanks.
