### ISSUE TITLE
About pcaudiolib licence.

### ISSUE THREAD

**Issue by fredvs** [rhdunn/pcaudiolib#14]
Hello.

May I use pcaudiolib for no open-source projects ?
Is it premised to add some methods to code (for example audio_object_read) ? 

Thanks.

Fre;D

**Comment by fredvs** [comment]
Hello.

Very sad that you do not answer.

Jonathan did choose for the output-sound library a project without any license (Portaudio).

IMHO, you did break the GPL spirit of eSpeak imposing your pcaudiolib GPL project.

Please, rename pcaudiolib into LGPL.

Thanks.

Fre;D

**Comment by rhdunn** [comment]
eSpeak is GPL (v3+), and pcaudiolib is GPL (v3+), therefore there is no license incompatibility or "break[ing] the GPL spirit of eSpeak".

As such, if you use pcaudiolib in your project by linking to the library, that project must be GPL as well. The same applies if you are linking to the eSpeak library. If you are calling the espeak binary, you don't need to GPL the project using it, but do need to provide the eSpeak sources on request.

Importing part of the project has the same effect, as that code is GPL licensed.

**Comment by fredvs** [comment]
Hello.

> If you are calling the espeak binary, you don't need to GPL the project using it, but do need to provide the eSpeak sources on request.

Huh, sorry, but if Pcaudiolib is GPL and if you adapt the code of it (for example adding Windows XP compatibility) you are not allowed to use eSpeak binary if your project is not GPL.

With original eSpeak, if you adapt Portaudio, you may still use eSpeak binary, even if your project is not GPL.

**Comment by rhdunn** [comment]
pcaudiolib is used by the espeak-ng program, not by the project using espeak. Therefore, if you call espeak-ng.exe in your program, your program is not linking to the GPL code, so does not need to be GPL.

If you adapt pcaudiolib for Windows XP compatibility, then build espeak-ng.exe and espeak-ng.dll with that, and call espeak-ng.exe from your own project, you don't need to make your project GPL. You only need to provide the pcaudiolib and espeak-ng code on request, per the GPL. This is because it is espeak-ng that is linking to pcaudiolib, not your project.

https://softwareengineering.stackexchange.com/questions/110380/call-gpl-software-from-non-gpl-software?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

Note that both eSpeak/eSpeak NG, and pcaudiolib are GPL.

**Comment by fredvs** [comment]
Hello and many thanks to answer.

It seems to me that you did not understand what I try to explain.

Take the example of Linux.

If you compile espeak-ng as executable, espeak-ng will need pcaudiolib as dependency.
If I do adapt pcaudiolib (for example for better latency or using float 32 resolution), I will have licence problems, even if project espeak was not changed.

May I ask you what would be problems for you if pcaudiolib was LGPL ?

> Note that both eSpeak/eSpeak NG, and pcaudiolib are GPL.

Huh not totally agreed.

 eSpeak is GPL, his output-sound library Portaudio is licence-free.
 eSpeak-NG is GPL, his output-sound library PCaudio is GPL.

**Comment by rhdunn** [comment]
It is the espeak-ng executable that is linking to pcaudiolib (as a DLL, shared object, or statically as is the case for the Visual Studio solution based Windows builds), not your project's application/executable. As long as your project is calling eSpeak NG via its command line interface, and you are using eSpeak NG to do the audio output (via pcaudiolib) -- i.e. you are not linking to pcaudiolib in your project -- then you don't have any problems.

You would only need to have pcaudiolib as LGPL if you intended to use it directly in your application. If you need audio in your application, you can use portaudio or any other audio APIs/libraries.

Additionally, you can disable the pcaudiolib support for espeak. In that case, you would need to use the `--stdout` option and handle the audio yourself.

**Comment by fredvs** [comment]
Hello.

Ha, this one is more clear. ;-)

But a licence-problem will remain if I change code of pcaudiolib even if it is used exclusively for eSpeak-NG executable from command line (not directly by the app).

The good news is that --stout option can be the safe solution.
I have to explore eSpeak-NG code to see how to use it. 
(Or, maybe, you have a demo of this...;-)) 

About Pcaudiolib, IMHO, LGPL would give him much more power, that could be very usefull for eSpeak-NG (and others).
But you are the boss, of course.

Thanks for your clarifications.

Fre;D
